name: Docker Build & Deploy (Self-Hosted)

on:
  push:
    branches:
      - main 

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx
  IMAGE_TAG: latest

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (optional)
        uses: docker/setup-buildx-action@v2

      - name: Docker Build
        run: |
          docker build -t $CONTAINER_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login $CONTAINER_REGISTRY -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Push
        run: |
          docker push $CONTAINER_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
