name: Exploring Variables and Secrets

on:
  push:

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Docker Build
        run: docker build -t ${{ env.CONTAINER_REGISTRY}}/lakshitladha007/$IMAGE_NAME:latest 

      - name: Docker Login
        run: docker login --username=lakshitladha007 --password=${{ secrets.DOCKER_PASSWORD}}

      - name: Docker Publish
        run: docker push $CONTAINER_REGISTRY/lakshitladha007/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: self-hosted
    steps:

      - name: Docker Run
        run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY}}/lakshitladha007/$IMAGE_NAME:latest